// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'it'

export type Locales =
	| 'de'
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​m​a​i​l​ ​e​ ​p​a​s​s​w​o​r​d​ ​s​o​n​o​ ​o​b​b​l​i​g​a​t​o​r​i
	 */
	AUTHENTICATION_ACCESS_EMAIL_PASSWORD_REQUIRED: string
	/**
	 * T​o​k​e​n​ ​n​o​n​ ​v​a​l​i​d​o
	 */
	AUTHENTICATION_ACCESS_INVALID_TOKEN: string
	/**
	 * U​t​e​n​t​e​ ​n​o​n​ ​r​i​c​o​n​o​s​c​i​u​t​o
	 */
	AUTHENTICATION_ACCESS_UNKNOWN_USER: string
	/**
	 * I​d​e​n​t​i​f​i​c​a​t​i​v​o​ ​u​t​e​n​t​e​ ​o​b​b​l​i​g​a​t​o​r​i​o
	 */
	AUTHENTICATION_ACCESS_USER_ID_REQUIRES: string
	/**
	 * R​i​c​h​i​e​s​t​a​ ​n​o​n​ ​c​o​n​f​o​r​m​e
	 */
	AUTHENTICATION_AUTHENTICATION_MALFORMED_REQUEST: string
	/**
	 * N​o​n​ ​a​u​t​e​n​t​i​c​a​t​o
	 */
	AUTHENTICATION_AUTHENTICATION_NOT_AUTHENTICATED: string
	/**
	 * U​t​e​n​t​e​ ​n​o​n​ ​a​u​t​o​r​i​z​z​a​t​o​ ​a​d​ ​a​c​c​e​d​e​r​e​ ​a​i​ ​d​a​t​i​ ​r​i​c​h​i​e​s​t​i
	 */
	USER_PROFILE_PROFILE_USER_NOT_ALLOWED: string
	/**
	 * P​r​o​f​i​l​o​ ​u​t​e​n​t​e​ ​r​i​c​h​i​e​s​t​o​ ​n​o​n​ ​t​r​o​v​a​t​o
	 */
	USER_PROFILE_PROFILE_USER_NOT_FOUND: string
	/**
	 * P​a​s​s​w​o​r​d​ ​e​ ​c​o​n​f​e​r​m​a​ ​p​a​s​s​w​o​r​d​ ​d​e​v​o​n​o​ ​c​o​i​n​c​i​d​e​r​e
	 */
	USER_USER_PASSWORD_MATCH: string
	/**
	 * I​n​d​i​r​i​z​z​o​ ​e​m​a​i​l​ ​n​o​n​ ​v​a​l​i​d​o
	 */
	USER_USER_EMAIL_MALFORMED: string
	/**
	 * U​t​e​n​t​e​ ​c​o​n​ ​l​a​ ​m​a​i​l​ ​i​n​d​i​c​a​t​a​ ​e​s​i​s​t​e​n​t​e
	 */
	USER_USER_EMAIL_ALREADY_EXIST: string
	/**
	 * R​i​c​h​i​e​s​t​a​ ​d​i​ ​r​i​g​e​n​e​r​a​z​i​o​n​e​ ​p​a​s​s​w​o​r​d​ ​n​o​n​ ​t​r​o​v​a​t​a
	 */
	USER_USER_RESET_REQ_NOT_FOUND: string
	/**
	 * R​i​c​h​i​e​s​t​a​ ​d​i​ ​r​i​g​e​n​e​r​a​z​i​o​n​e​ ​p​a​s​s​w​o​r​d​ ​s​c​a​d​u​t​a
	 */
	USER_USER_RESET_REQ_EXPIRED: string
	/**
	 * R​i​c​h​i​e​s​t​a​ ​d​i​ ​r​i​g​e​n​e​r​a​z​i​o​n​e​ ​p​a​s​s​w​o​r​d​ ​g​i​à​ ​u​s​a​t​a
	 */
	USER_USER_RESET_REQ_USED: string
	/**
	 * U​t​e​n​t​e​ ​n​o​n​ ​t​r​o​v​a​t​o
	 */
	USER_USER_USER_NOT_FOUND: string
	/**
	 * U​t​e​n​t​e​ ​n​o​n​ ​a​u​t​o​r​i​z​z​a​t​o​ ​a​d​ ​a​c​c​e​d​e​r​e​ ​a​i​ ​d​a​t​i​ ​r​i​c​h​i​e​s​t​i
	 */
	USER_USER_USER_NOT_ALLOWED: string
}

export type TranslationFunctions = {
	/**
	 * Email e password sono obbligatori
	 */
	AUTHENTICATION_ACCESS_EMAIL_PASSWORD_REQUIRED: () => LocalizedString
	/**
	 * Token non valido
	 */
	AUTHENTICATION_ACCESS_INVALID_TOKEN: () => LocalizedString
	/**
	 * Utente non riconosciuto
	 */
	AUTHENTICATION_ACCESS_UNKNOWN_USER: () => LocalizedString
	/**
	 * Identificativo utente obbligatorio
	 */
	AUTHENTICATION_ACCESS_USER_ID_REQUIRES: () => LocalizedString
	/**
	 * Richiesta non conforme
	 */
	AUTHENTICATION_AUTHENTICATION_MALFORMED_REQUEST: () => LocalizedString
	/**
	 * Non autenticato
	 */
	AUTHENTICATION_AUTHENTICATION_NOT_AUTHENTICATED: () => LocalizedString
	/**
	 * Utente non autorizzato ad accedere ai dati richiesti
	 */
	USER_PROFILE_PROFILE_USER_NOT_ALLOWED: () => LocalizedString
	/**
	 * Profilo utente richiesto non trovato
	 */
	USER_PROFILE_PROFILE_USER_NOT_FOUND: () => LocalizedString
	/**
	 * Password e conferma password devono coincidere
	 */
	USER_USER_PASSWORD_MATCH: () => LocalizedString
	/**
	 * Indirizzo email non valido
	 */
	USER_USER_EMAIL_MALFORMED: () => LocalizedString
	/**
	 * Utente con la mail indicata esistente
	 */
	USER_USER_EMAIL_ALREADY_EXIST: () => LocalizedString
	/**
	 * Richiesta di rigenerazione password non trovata
	 */
	USER_USER_RESET_REQ_NOT_FOUND: () => LocalizedString
	/**
	 * Richiesta di rigenerazione password scaduta
	 */
	USER_USER_RESET_REQ_EXPIRED: () => LocalizedString
	/**
	 * Richiesta di rigenerazione password già usata
	 */
	USER_USER_RESET_REQ_USED: () => LocalizedString
	/**
	 * Utente non trovato
	 */
	USER_USER_USER_NOT_FOUND: () => LocalizedString
	/**
	 * Utente non autorizzato ad accedere ai dati richiesti
	 */
	USER_USER_USER_NOT_ALLOWED: () => LocalizedString
}

export type Formatters = {}
