// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'it'

export type Locales =
	| 'de'
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​m​a​i​l​ ​e​ ​p​a​s​s​w​o​r​d​ ​s​o​n​o​ ​o​b​b​l​i​g​a​t​o​r​i
	 */
	AUTHENTICATION_ACCESS_EMAIL_PASSWORD_REQUIRED: string
	/**
	 * T​o​k​e​n​ ​n​o​n​ ​v​a​l​i​d​o
	 */
	AUTHENTICATION_ACCESS_INVALID_TOKEN: string
	/**
	 * U​t​e​n​t​e​ ​n​o​n​ ​r​i​c​o​n​o​s​c​i​u​t​o
	 */
	AUTHENTICATION_ACCESS_UNKNOWN_USER: string
	/**
	 * I​d​e​n​t​i​f​i​c​a​t​i​v​o​ ​u​t​e​n​t​e​ ​o​b​b​l​i​g​a​t​o​r​i​o
	 */
	AUTHENTICATION_ACCESS_USER_ID_REQUIRES: string
	/**
	 * R​i​c​h​i​e​s​t​a​ ​n​o​n​ ​c​o​n​f​o​r​m​e
	 */
	AUTHENTICATION_AUTHENTICATION_MALFORMED_REQUEST: string
	/**
	 * N​o​n​ ​a​u​t​e​n​t​i​c​a​t​o
	 */
	AUTHENTICATION_AUTHENTICATION_NOT_AUTHENTICATED: string
	/**
	 * U​t​e​n​t​e​ ​n​o​n​ ​a​u​t​o​r​i​z​z​a​t​o​ ​a​d​ ​a​c​c​e​d​e​r​e​ ​a​i​ ​d​a​t​i​ ​r​i​c​h​i​e​s​t​i
	 */
	USER_PROFILE_PROFILE_USER_NOT_ALLOWED: string
	/**
	 * P​r​o​f​i​l​o​ ​u​t​e​n​t​e​ ​r​i​c​h​i​e​s​t​o​ ​n​o​n​ ​t​r​o​v​a​t​o
	 */
	USER_PROFILE_PROFILE_USER_NOT_FOUND: string
	/**
	 * P​a​s​s​w​o​r​d​ ​e​ ​c​o​n​f​e​r​m​a​ ​p​a​s​s​w​o​r​d​ ​d​e​v​o​n​o​ ​c​o​i​n​c​i​d​e​r​e
	 */
	USER_USER_PASSWORD_MATCH: string
	/**
	 * P​a​s​s​w​o​r​d​ ​n​o​n​ ​c​o​n​f​o​r​m​e​ ​a​i​ ​r​e​q​u​i​s​i​t​i​ ​r​i​c​h​i​e​s​t​i
	 */
	USER_USER_PASSWORD_NOT_COMPLIANT: string
	/**
	 * I​n​d​i​r​i​z​z​o​ ​e​m​a​i​l​ ​n​o​n​ ​v​a​l​i​d​o
	 */
	USER_USER_EMAIL_MALFORMED: string
	/**
	 * U​t​e​n​t​e​ ​c​o​n​ ​l​a​ ​m​a​i​l​ ​i​n​d​i​c​a​t​a​ ​e​s​i​s​t​e​n​t​e
	 */
	USER_USER_EMAIL_ALREADY_EXIST: string
	/**
	 * R​i​c​h​i​e​s​t​a​ ​d​i​ ​r​i​g​e​n​e​r​a​z​i​o​n​e​ ​p​a​s​s​w​o​r​d​ ​n​o​n​ ​t​r​o​v​a​t​a
	 */
	USER_USER_RESET_REQ_NOT_FOUND: string
	/**
	 * R​i​c​h​i​e​s​t​a​ ​d​i​ ​r​i​g​e​n​e​r​a​z​i​o​n​e​ ​p​a​s​s​w​o​r​d​ ​s​c​a​d​u​t​a
	 */
	USER_USER_RESET_REQ_EXPIRED: string
	/**
	 * R​i​c​h​i​e​s​t​a​ ​d​i​ ​r​i​g​e​n​e​r​a​z​i​o​n​e​ ​p​a​s​s​w​o​r​d​ ​g​i​à​ ​u​s​a​t​a
	 */
	USER_USER_RESET_REQ_USED: string
	/**
	 * U​t​e​n​t​e​ ​n​o​n​ ​t​r​o​v​a​t​o
	 */
	USER_USER_USER_NOT_FOUND: string
	/**
	 * U​t​e​n​t​e​ ​n​o​n​ ​a​u​t​o​r​i​z​z​a​t​o​ ​a​d​ ​a​c​c​e​d​e​r​e​ ​a​i​ ​d​a​t​i​ ​r​i​c​h​i​e​s​t​i
	 */
	USER_USER_USER_NOT_ALLOWED: string
	/**
	 * P​a​s​s​w​o​r​d​ ​p​r​e​c​e​d​e​n​t​e​ ​n​o​n​ ​c​o​r​r​e​t​t​a
	 */
	USER_USER_OLD_PASSWORD: string
	/**
	 * P​a​s​s​w​o​r​d​ ​g​i​à​ ​u​s​a​t​a​ ​i​n​ ​p​r​e​c​e​d​e​n​z​a
	 */
	USER_USER_USED_PASSWORD: string
	/**
	 * R​i​c​h​i​e​s​t​a​ ​r​i​p​r​i​s​t​i​n​o​ ​p​a​s​s​w​o​r​d
	 */
	USER_USER_PASSWORD_RESET_EMAIL_SUBJECT: string
	/**
	 * C​i​a​o​ ​{​n​a​m​e​}​,​<​b​r​>​è​ ​s​t​a​t​o​ ​r​i​c​h​i​e​s​t​o​ ​i​l​ ​r​i​p​r​i​s​t​i​n​o​ ​d​e​l​l​a​ ​t​u​a​ ​p​a​s​s​w​o​r​d​.​ ​P​e​r​ ​p​r​o​c​e​d​e​r​e​ ​c​l​i​c​c​a​ ​s​u​l​ ​l​i​n​k​ ​s​e​g​u​e​n​t​e​.​<​b​r​>​<​a​ ​h​r​e​f​=​"​{​l​i​n​k​}​"​>​R​i​p​r​i​s​t​i​n​a​ ​p​a​s​s​w​o​r​d​<​/​a​>
	 * @param {string} link
	 * @param {string} name
	 */
	USER_USER_PASSWORD_RESET_EMAIL_BODY_HTML: RequiredParams<'link' | 'name'>
	/**
	 * C​i​a​o​ ​{​n​a​m​e​}​,​
​è​ ​s​t​a​t​o​ ​r​i​c​h​i​e​s​t​o​ ​i​l​ ​r​i​p​r​i​s​t​i​n​o​ ​d​e​l​l​a​ ​t​u​a​ ​p​a​s​s​w​o​r​d​.​ ​P​e​r​ ​p​r​o​c​e​d​e​r​e​ ​c​l​i​c​c​a​ ​s​u​l​ ​l​i​n​k​ ​s​e​g​u​e​n​t​e​.​
​{​l​i​n​k​}
	 * @param {string} link
	 * @param {string} name
	 */
	USER_USER_PASSWORD_RESET_EMAIL_BODY_TEXT: RequiredParams<'link' | 'name'>
	/**
	 * C​o​n​f​e​r​m​a​ ​r​i​p​r​i​s​t​i​n​o​ ​p​a​s​s​w​o​r​d
	 */
	USER_USER_PASSWORD_RESET_CONFIRM_EMAIL_SUBJECT: string
	/**
	 * C​i​a​o​ ​{​n​a​m​e​}​,​<​b​r​>​l​a​ ​t​u​a​ ​p​a​s​s​w​o​r​d​ ​è​ ​s​t​a​t​a​ ​r​i​p​r​i​s​t​i​n​a​t​a​.​ ​P​e​r​ ​a​c​c​e​d​e​r​e​ ​c​l​i​c​c​a​ ​s​u​l​ ​l​i​n​k​ ​s​e​g​u​e​n​t​e​.​<​b​r​>​<​a​ ​h​r​e​f​=​"​{​l​i​n​k​}​"​>​A​c​c​e​d​i​ ​a​d​ ​A​s​s​i​h​u​b​<​/​a​>
	 * @param {string} link
	 * @param {string} name
	 */
	USER_USER_PASSWORD_RESET_CONFIRM_EMAIL_BODY_HTML: RequiredParams<'link' | 'name'>
	/**
	 * C​i​a​o​ ​{​n​a​m​e​}​,​
​l​a​ ​t​u​a​ ​p​a​s​s​w​o​r​d​ ​è​ ​s​t​a​t​a​ ​r​i​p​r​i​s​t​i​n​a​t​a​.​ ​P​e​r​ ​a​c​c​e​d​e​r​e​ ​c​l​i​c​c​a​ ​s​u​l​ ​l​i​n​k​ ​s​e​g​u​e​n​t​e​.​
​{​l​i​n​k​}
	 * @param {string} link
	 * @param {string} name
	 */
	USER_USER_PASSWORD_RESET_CONFIRM_EMAIL_BODY_TEXT: RequiredParams<'link' | 'name'>
	/**
	 * R​e​g​i​s​t​r​a​z​i​o​n​e​ ​c​o​n​f​e​r​m​a​t​a
	 */
	USER_USER_PASSWORD_REGISTER_EMAIL_SUBJECT: string
	/**
	 * C​i​a​o​ ​{​n​a​m​e​}​,​<​b​r​>​s​e​i​ ​s​t​a​t​o​ ​c​o​r​r​e​t​t​a​m​e​n​t​e​ ​r​e​g​i​s​t​r​a​t​o​ ​s​u​ ​A​s​s​i​h​u​b​.​ ​A​t​t​e​n​d​i​ ​c​h​e​ ​u​n​ ​a​m​m​i​n​i​s​t​r​a​t​o​r​e​ ​a​b​i​l​i​t​i​ ​i​l​ ​t​u​o​ ​a​c​c​o​u​n​t​.
	 * @param {string} name
	 */
	USER_USER_PASSWORD_REGISTER_EMAIL_BODY_HTML: RequiredParams<'name'>
	/**
	 * C​i​a​o​ ​{​n​a​m​e​}​,​
​s​e​i​ ​s​t​a​t​o​ ​c​o​r​r​e​t​t​a​m​e​n​t​e​ ​r​e​g​i​s​t​r​a​t​o​ ​s​u​ ​A​s​s​i​h​u​b​.​ ​A​t​t​e​n​d​i​ ​c​h​e​ ​u​n​ ​a​m​m​i​n​i​s​t​r​a​t​o​r​e​ ​a​b​i​l​i​t​i​ ​i​l​ ​t​u​o​ ​a​c​c​o​u​t​.​

	 * @param {string} name
	 */
	USER_USER_PASSWORD_REGISTER_EMAIL_BODY_TEXT: RequiredParams<'name'>
	/**
	 * A​t​t​i​v​a​z​i​o​n​e​ ​c​o​n​f​e​r​m​a​t​a
	 */
	USER_USER_ACTIVATED_EMAIL_SUBJECT: string
	/**
	 * C​i​a​o​ ​{​n​a​m​e​}​,​<​b​r​>​i​l​ ​t​u​o​ ​a​c​c​o​u​n​t​ ​è​ ​s​t​a​t​o​ ​a​t​t​i​v​a​t​o​ ​d​a​ ​u​n​ ​a​m​m​i​n​i​s​t​r​a​t​o​r​e​.​ ​P​e​r​ ​a​c​c​e​d​e​r​e​ ​c​l​i​c​c​a​ ​s​u​l​ ​l​i​n​k​ ​s​e​g​u​e​n​t​e​.​<​b​r​>​<​a​ ​h​r​e​f​=​"​{​l​i​n​k​}​"​>​A​c​c​e​d​i​ ​a​d​ ​A​s​s​i​h​u​b​<​/​a​>
	 * @param {string} link
	 * @param {string} name
	 */
	USER_USER_ACTIVATED_EMAIL_BODY_HTML: RequiredParams<'link' | 'name'>
	/**
	 * C​i​a​o​ ​{​n​a​m​e​}​,​
​s​e​i​ ​s​t​a​t​o​ ​c​o​r​r​e​t​t​a​m​e​n​t​e​ ​r​e​g​i​s​t​r​a​t​o​ ​s​u​ ​A​s​s​i​h​u​b​.​ ​P​e​r​ ​a​c​c​e​d​e​r​e​ ​c​l​i​c​c​a​ ​s​u​ ​l​i​n​k​ ​s​e​g​u​e​n​t​e​.​
​{​l​i​n​k​}
	 * @param {string} link
	 * @param {string} name
	 */
	USER_USER_ACTIVATED_EMAIL_BODY_TEXT: RequiredParams<'link' | 'name'>
}

export type TranslationFunctions = {
	/**
	 * Email e password sono obbligatori
	 */
	AUTHENTICATION_ACCESS_EMAIL_PASSWORD_REQUIRED: () => LocalizedString
	/**
	 * Token non valido
	 */
	AUTHENTICATION_ACCESS_INVALID_TOKEN: () => LocalizedString
	/**
	 * Utente non riconosciuto
	 */
	AUTHENTICATION_ACCESS_UNKNOWN_USER: () => LocalizedString
	/**
	 * Identificativo utente obbligatorio
	 */
	AUTHENTICATION_ACCESS_USER_ID_REQUIRES: () => LocalizedString
	/**
	 * Richiesta non conforme
	 */
	AUTHENTICATION_AUTHENTICATION_MALFORMED_REQUEST: () => LocalizedString
	/**
	 * Non autenticato
	 */
	AUTHENTICATION_AUTHENTICATION_NOT_AUTHENTICATED: () => LocalizedString
	/**
	 * Utente non autorizzato ad accedere ai dati richiesti
	 */
	USER_PROFILE_PROFILE_USER_NOT_ALLOWED: () => LocalizedString
	/**
	 * Profilo utente richiesto non trovato
	 */
	USER_PROFILE_PROFILE_USER_NOT_FOUND: () => LocalizedString
	/**
	 * Password e conferma password devono coincidere
	 */
	USER_USER_PASSWORD_MATCH: () => LocalizedString
	/**
	 * Password non conforme ai requisiti richiesti
	 */
	USER_USER_PASSWORD_NOT_COMPLIANT: () => LocalizedString
	/**
	 * Indirizzo email non valido
	 */
	USER_USER_EMAIL_MALFORMED: () => LocalizedString
	/**
	 * Utente con la mail indicata esistente
	 */
	USER_USER_EMAIL_ALREADY_EXIST: () => LocalizedString
	/**
	 * Richiesta di rigenerazione password non trovata
	 */
	USER_USER_RESET_REQ_NOT_FOUND: () => LocalizedString
	/**
	 * Richiesta di rigenerazione password scaduta
	 */
	USER_USER_RESET_REQ_EXPIRED: () => LocalizedString
	/**
	 * Richiesta di rigenerazione password già usata
	 */
	USER_USER_RESET_REQ_USED: () => LocalizedString
	/**
	 * Utente non trovato
	 */
	USER_USER_USER_NOT_FOUND: () => LocalizedString
	/**
	 * Utente non autorizzato ad accedere ai dati richiesti
	 */
	USER_USER_USER_NOT_ALLOWED: () => LocalizedString
	/**
	 * Password precedente non corretta
	 */
	USER_USER_OLD_PASSWORD: () => LocalizedString
	/**
	 * Password già usata in precedenza
	 */
	USER_USER_USED_PASSWORD: () => LocalizedString
	/**
	 * Richiesta ripristino password
	 */
	USER_USER_PASSWORD_RESET_EMAIL_SUBJECT: () => LocalizedString
	/**
	 * Ciao {name},<br>è stato richiesto il ripristino della tua password. Per procedere clicca sul link seguente.<br><a href="{link}">Ripristina password</a>
	 */
	USER_USER_PASSWORD_RESET_EMAIL_BODY_HTML: (arg: { link: string, name: string }) => LocalizedString
	/**
	 * Ciao {name},
è stato richiesto il ripristino della tua password. Per procedere clicca sul link seguente.
{link}
	 */
	USER_USER_PASSWORD_RESET_EMAIL_BODY_TEXT: (arg: { link: string, name: string }) => LocalizedString
	/**
	 * Conferma ripristino password
	 */
	USER_USER_PASSWORD_RESET_CONFIRM_EMAIL_SUBJECT: () => LocalizedString
	/**
	 * Ciao {name},<br>la tua password è stata ripristinata. Per accedere clicca sul link seguente.<br><a href="{link}">Accedi ad Assihub</a>
	 */
	USER_USER_PASSWORD_RESET_CONFIRM_EMAIL_BODY_HTML: (arg: { link: string, name: string }) => LocalizedString
	/**
	 * Ciao {name},
la tua password è stata ripristinata. Per accedere clicca sul link seguente.
{link}
	 */
	USER_USER_PASSWORD_RESET_CONFIRM_EMAIL_BODY_TEXT: (arg: { link: string, name: string }) => LocalizedString
	/**
	 * Registrazione confermata
	 */
	USER_USER_PASSWORD_REGISTER_EMAIL_SUBJECT: () => LocalizedString
	/**
	 * Ciao {name},<br>sei stato correttamente registrato su Assihub. Attendi che un amministratore abiliti il tuo account.
	 */
	USER_USER_PASSWORD_REGISTER_EMAIL_BODY_HTML: (arg: { name: string }) => LocalizedString
	/**
	 * Ciao {name},
sei stato correttamente registrato su Assihub. Attendi che un amministratore abiliti il tuo accout.

	 */
	USER_USER_PASSWORD_REGISTER_EMAIL_BODY_TEXT: (arg: { name: string }) => LocalizedString
	/**
	 * Attivazione confermata
	 */
	USER_USER_ACTIVATED_EMAIL_SUBJECT: () => LocalizedString
	/**
	 * Ciao {name},<br>il tuo account è stato attivato da un amministratore. Per accedere clicca sul link seguente.<br><a href="{link}">Accedi ad Assihub</a>
	 */
	USER_USER_ACTIVATED_EMAIL_BODY_HTML: (arg: { link: string, name: string }) => LocalizedString
	/**
	 * Ciao {name},
sei stato correttamente registrato su Assihub. Per accedere clicca su link seguente.
{link}
	 */
	USER_USER_ACTIVATED_EMAIL_BODY_TEXT: (arg: { link: string, name: string }) => LocalizedString
}

export type Formatters = {}
