
ALTER TABLE public."NotificationMessage" 
ADD COLUMN "entityId" BIGINT
;

ALTER TABLE "NotificationMessage"
	ALTER COLUMN "userId" TYPE BIGINT,
	ALTER COLUMN "userId" SET NOT NULL,
	ALTER COLUMN "userId" DROP DEFAULT;

ALTER TABLE "FileEntry"
	ALTER COLUMN "userId" TYPE BIGINT,
	ALTER COLUMN "userId" SET NOT NULL,
	ALTER COLUMN "userId" DROP DEFAULT;

ALTER TABLE "UserPasswordHistory"
	ALTER COLUMN "userId" TYPE BIGINT,
	ALTER COLUMN "userId" SET NOT NULL,
	ALTER COLUMN "userId" DROP DEFAULT;

ALTER TABLE "UserPasswordReset"
	ALTER COLUMN "userId" TYPE BIGINT,
	ALTER COLUMN "userId" SET NOT NULL,
	ALTER COLUMN "userId" DROP DEFAULT;

